context:
  version: 4.2.0

package:
  name: gotop
  version: ${{ version }}

source:
  url: https://github.com/xxxserxxx/gotop/archive/v${{ version }}.tar.gz
  sha256: e9d9041903acb6bd3ffe94e0a02e69eea53f1128274da1bfe00fe44331ccceb1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-cgo') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - go-licenses

tests:
  - script:
      - gotop --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal based graphical activity monitor inspired by gtop and vtop
  homepage: https://github.com/xxxserxxx/gotop
  repository: https://github.com/xxxserxxx/gotop

extra:
  recipe-maintainers:
    - danielnachun
